//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Kondakov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int ContentId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliverDate { get; set; }
        public int PickupPointId { get; set; }
        public int ClientId { get; set; }
        public int ObtainCode { get; set; }
        public int StatusId { get; set; }
    
        public virtual OrderContent OrderContent { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
