//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Kondakov
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderContents = new HashSet<OrderContent>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliverDate { get; set; }
        public int PickupPointId { get; set; }
        public int ClientId { get; set; }
        public int ObtainCode { get; set; }
        public int StatusId { get; set; }

        public string OrderArticles
        {
            get
            {
                if (OrderContents == null || OrderContents.Count == 0)
                {
                    return "Нет товаров";
                }
                return string.Join(", ", OrderContents.Where(c => c.Product != null).Select(c => c.Product.Article));
            }
        }

        public string PickupAddressText
        {
            get
            {
                if (PickupPoint == null)
                {
                    return "Не указан";
                }
                return PickupPoint.FullAddress;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContent> OrderContents { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
