//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Kondakov
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }

        public double UnitPrice
        {
            get
            {
                if (Product == null) return 0;
                return Product.priceDiscount ?? Product.Price;
            }
        }

        public double TotalPrice
        {
            get
            {
                return UnitPrice * Count;
            }
        }

        public string ProductTitle
        {
            get
            {
                if (Product == null) return "Товар";
                return Product.ProductName != null ? Product.ProductName.Name : Product.Description;
            }
        }
    }
}
