//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Kondakov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderContents = new HashSet<OrderContent>();
        }

        public int Id { get; set; }
        public string Article { get; set; }
        public int NameId { get; set; }
        public string Unit { get; set; }
        public double Price { get; set; }
        public int SupplierId { get; set; }
        public int ManufacturerId { get; set; }
        public int ProductCategoryId { get; set; }
        public int Discount { get; set; }
        public string DiscountText => Discount.ToString() + "%";
        public int Count { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }

        public bool isDiscount => Discount > 15;
        public bool isOnSale => Discount > 0;
        public double? priceDiscount
        {
            get
            {
                return Price - (Price * Discount / 100);
            }
        }
        public bool isQuantity => Count <= 0;

        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContent> OrderContents { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
